# Автор MishaNeYT, плагин сделал для общего использования.
# Запрещено выдавать плагин за себя.

Settings:
  # Права для администрации. Используется для ввода основной команды.
  # (Default: mb.admin)
  Permission: 'mb.admin'
  # Если возникли проблемы с сохранением, используйте эту функцию.
  # (Default: true)
  AdvanceReload: true

  Depends:
    # Если возникли проблемы с Vault, я рекомендую отключть его.
    # (Default: false)
    Vault: false

  SoftDepends:
    # Если возникли проблемы с PlaceholderAPI, я рекомендую отключть его.
    # (Default: false)
    Placeholder: false

  MineProtection:
    # true - игроки в режиме креатив смогут копать блоки.
    # (Default: false)
    BreakCreative: false
    # true - игроки с включенным флаям смогут копать блоки.
    # (Default: false)
    BreakFly: false

  # Здесь находятся миры, в которых работает плагин.
  Worlds:
    - world
    - mine

SoundPickup:
  # Воспроизводится звук после добычи блока.
  # (Default: true)
  Enabled: true
  # Список звуков https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  # Используйте только те звуки, которые поддерживаются в вашей версии сервера.
  Sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
  # Звук для MineProtection.
  ErrorSound: 'BLOCK_ANVIL_DESTROY'

# Сообщение на экран (Title). Сообщение можно редактировать в
# конфигурации messages.yml.
# (Default: false)
TitlePickup:
  Enabled: false
  FadeIn: 10
  Stay: 20
  FadeOut: 10

# Сообщение снизу (Action bar). Сообщение можно редактировать в
# конфигурации messages.yml.
# (Default: true)
Actionbar:
  Enabled: true

# Сообщение в чат. Сообщение можно редактировать в конфигурации
# messages.yml.
# (Default: false)
MessageChat:
  Enabled: false