# Создатель GhostSetuper (MishaNeYT). Появилась проблема? Пишите мне во вконтакте https://vk.com/mishapavlovyakutsk

# НЕМНОГО ОБ АВТОРСКОМ ПРАВЕ:
# Публикация плагина без моего разрешения строго запрещена! Все мы знаем об авторском праве, поэтому соблюдайте его.
# Я ведь для вас стараюсь.

# Есть открытый исходный код, вот ссылочка: https://github.com/MishaNeYT/MiningBlock

Settings:
  # Права для администрации сервера.
  Permission: mb.admin
  # Если возникли проблемы с Vault, то вы можете отключить его.
  EnableVault: false
  # Если TRUE, то игроки с КРЕАТИВОВ не смогут добывать блоки - они просто не будут падать.
  BreakCreative: true
  # Уведомления в чат об ошибках в конфиге mining.yml. Если бесит, то можете отключить
  InfoErrorChat: true
  # Надпись на экране, о том, что у игрока заполненный инвентарь. Чисто хайпиксель xD
  EnableFullInventory: true
  # Миры, в которых работают блоки из mining.yml.
  EnableWorlds:
    - world
    - spawn

SoundPickup:
  # Воспроизводится звук добытой руды.
  Enable: true
  # Список доступных звуков https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  Sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'

# Сообщение в экран (Title).
TitleOnPickup:
  Enable: false
  Title: '&aУспех!'
  Subtitle: '&fВы заработали &e+%money%$'
  FadeIn: 10
  Stay: 20
  FadeOut: 10

# Сообщение снизу (Action bar).
Actionbar:
  Enable: true
  Message: '&e+%money%$ монет'

# Сообщение в чате.
MessageToChat:
  Enable: false
  Message: '&e+%money%$ монет'

Messages:
  NoPerms: '&cУ вас нет прав для использования этой команды.'
  OnlyPlayer: '&cКоманду может ввести только игрок.'
  ErrorCmd: '&cКоманда введена неправильно. Используйте /mb help'
  Reload: '&6[MB] &fПлагин успешно перезагружен.'
  FullInventory:
    Title: '&4Ваш инвентарь заполнился!'
    Subtitle: '&cОсвободите место, чтобы добыть блок.'
  EditOre:
    Enable: '&6[MB] &fВы &aвключили &fрежим редактирования руд.'
    Disable: '&6[MB] &fВы &cотключили &fрежим редактирования руд.'
  HelpCommand:
    - ''
    - '&6--------------------------------------------------'
    - '&f Создатель плагина: &6GhostSetuper'
    - '&f Версия плагина: &a%version%'
    - ''
    - '&8 ▸ &e/miningblock menu &7- &fоткрыть GUI;'
    - '&8 ▸ &e/miningblock info &7- &fкнига для чайникам.'
    - '&8 ▸ &e/miningblock editore &7- &fвключить редактирования руд.'
    - '&8 ▸ &e/miningblock reload &7- &fперезагрузить плагин.'
    - '&6--------------------------------------------------'
    - ''