# Зависимость Vault и PlaceholderAPI
# Свои placeholder-ы - %money% и %player%.

Settings:
  EnableVault: true # Если проблемы, то можете отключить Vault.
  EnableEditOre: false
  Permission: miningblock.admin
  EnableWorld: # Разрешённые миры - в которых будет работать шахта.
  - world
  - miner

Sound:
  EnableSoundPickup: false # Производится звук сломанной руды.
  SoundPickup: ENTITY_EXPERIENCE_ORB_PICKUP # Сам звук https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

# Сообщение в экран (Титл).
TitleOnPickup:
  EnableTitles: false
  Title: '&aУспешно'
  Subtitle: '&fВы заработали &e+%money%$'
  FadeIn: 10
  Stay: 20
  FadeOut: 10

# Сообщение снизу (Нижний бар).
Actionbar:
  EnableActionbar: true
  Message: '&e+%money%$ монеты'

# Сообщение в чате.
MessageToChat:
  EnableMessageToChat: false
  Message:
  - '&a(!) &fВы заработали с этого блока &e+%money%$'

Messages:
  Reload: '&a✔ Плагин успешно перезагружен!'
  NoPerm: '&c✖ У вас нет прав!'
  Error: '&c✖ Команда введена не правильно!'
  CommandOnlyServer: '&c✖ Команда доступна только в игре!'
  UseCommand:
    - ''
    - '&6--------------------------------------------------'
    - '&f Создатель плагина: &7GhostSetuper'
    - '&f Версия плагина: &a%version%'
    - ''
    - '&8 ▸ &e/miningblock menu &f- открыть GUI;'
    - '&8 ▸ &e/miningblock reload &f- перезагрузить плагин.'
    - '&6--------------------------------------------------'
    - ''