name: MiningBlock
main: ru.mishaneyt.miningblock.Main
version: 2.2.0

authors: [ MishaNeYT ]
website: https://discord.gg/Nz6tNVBN56

depend: [ Vault ]
softdepend: [ PlaceholderAPI ]

api-version: 1.13

commands:
  miningblock:
    aliases: [ mb ]