name: MiningBlock
version: 2.0.0

main: ru.mishaneyt.miningblock.Main
authors: [ GhostSetuper ]

api-version: 1.13

commands:
  miningblock:
    description: Основная команда
    default: op
    aliases: [ mb ]