name: MiningBlock
version: 2.1.1

main: ru.mishaneyt.miningblock.Main
authors: [ GhostSetuper ]
website: https://vk.com/pleasantvkchannel

api-version: 1.13

commands:
  miningblock:
    default: op
    aliases: [ mb ]