name: MiningBlock
main: ru.mishaneyt.miningblock.Main
version: 2.1.1

authors: [ MishaNeYT ]
website: https://vk.com/pleasantvkchannel

api-version: 1.13

commands:
  miningblock:
    default: op
    aliases: [ mb ]
